const GAME_STATUS_PLAYING = 1;
const GAME_STATUS_WIN = 2;
const GAME_STATUS_GAMEOVER = 0;
const GAME_EXIT = -1;
module.exports = {GAME_STATUS_PLAYING, GAME_STATUS_GAMEOVER, GAME_STATUS_WIN, GAME_EXIT};
