const GAME_STATUS_PLAYING = 1;
const GAME_STATUS_WIN = 2;
const GAME_STATUS_OVER = 0;
const GAME_STATUS_EXIT = -1;
module.exports = {GAME_STATUS_PLAYING, GAME_STATUS_OVER, GAME_STATUS_WIN, GAME_STATUS_EXIT};
